@extends('layouts.admin')
@section('title','Roles & Permissions')
@section('page_title','Roles & Permissions')
@section('page_description','Create custom roles and define their effective workflow capabilities.')
@section('content')
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
<div class="card mb-3"><div class="card-header"><h3 class="card-title">Create custom role</h3></div><form method="POST" action="{{ route('admin.staff.roles.store') }}">@csrf<div class="card-body"><div class="form-row"><div class="form-group col-md-4"><label>Role name</label><input name="name" class="form-control" required></div><div class="form-group col-md-4"><label>Slug <span class="text-muted">(optional)</span></label><input name="slug" class="form-control" placeholder="faculty-coordinator"></div><div class="form-group col-md-4"><label>Description</label><input name="description" class="form-control"></div></div><div class="row">@foreach($permissions as $permission)<div class="col-md-6 col-lg-4"><div class="custom-control custom-checkbox mb-2"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" class="custom-control-input" id="newp{{ $permission->id }}"><label class="custom-control-label" for="newp{{ $permission->id }}">{{ $permission->name }} <code>{{ $permission->slug }}</code></label></div></div>@endforeach</div></div><div class="card-footer"><button class="btn btn-primary">Create role</button></div></form></div>
<div class="row">@foreach($roles as $role)<div class="col-lg-6 mb-3"><div class="card h-100"><form method="POST" action="{{ route('admin.staff.roles.update',$role) }}">@csrf @method('PUT')<div class="card-header"><h3 class="card-title">{{ $role->name }}</h3><span class="ml-auto badge badge-light">{{ $role->users_count }} users</span></div><div class="card-body"><div class="form-row"><div class="form-group col-md-6"><label>Name</label><input name="name" class="form-control" value="{{ $role->name }}" required></div><div class="form-group col-md-6"><label>Slug</label><input name="slug" class="form-control" value="{{ $role->slug }}" required></div></div><div class="form-group"><label>Description</label><textarea name="description" class="form-control" rows="2">{{ $role->description }}</textarea></div><label>Permissions</label><div class="row">@foreach($permissions as $permission)<div class="col-md-6"><div class="custom-control custom-checkbox mb-2"><input type="checkbox" name="permissions[]" value="{{ $permission->id }}" class="custom-control-input" id="r{{ $role->id }}p{{ $permission->id }}" @checked($role->permissions->contains($permission->id))><label class="custom-control-label" for="r{{ $role->id }}p{{ $permission->id }}">{{ $permission->name }}</label></div></div>@endforeach</div></div><div class="card-footer text-right"><button class="btn btn-primary">Save role</button></div></form></div></div>@endforeach</div>
@endsection
