@extends('layouts.admin')
@section('title','Application Progress')
@section('page_title','Application Progress')
@section('page_description',$application->reference_number.' — '.$application->applicationWindow->name)
@section('content')
<div class="row"><div class="col-lg-8"><div class="card"><div class="card-header d-flex justify-content-between align-items-center"><strong>Workflow progress</strong><span class="badge badge-primary">{{ str_replace('_',' ',$application->status) }}</span></div><div class="card-body">
@php $currentOrder=$application->workflow?->currentStage?->stage_order ?? 0; $completed=$application->workflow?->completed_at; @endphp
@foreach($application->workflow?->version?->stages?->sortBy('stage_order') ?? collect() as $stage)
@php $isCurrent=$application->workflow?->current_stage_id===$stage->id; $isDone=$completed || $stage->stage_order < $currentOrder; $rejected=$application->status==='REJECTED' && $isCurrent; @endphp
<div class="d-flex mb-4"><div class="mr-3 text-center" style="width:42px"><span class="d-inline-flex align-items-center justify-content-center rounded-circle {{ $rejected?'bg-danger':($isDone?'bg-success':($isCurrent?'bg-primary':'bg-light')) }} {{ ($isDone||$isCurrent||$rejected)?'text-white':'text-muted' }}" style="width:36px;height:36px">@if($rejected)<i class="fas fa-times"></i>@elseif($isDone)<i class="fas fa-check"></i>@else{{ $stage->stage_order }}@endif</span></div><div class="flex-grow-1"><div class="d-flex justify-content-between"><strong>{{ $stage->name }}</strong>@if($stage->is_final)<span class="badge badge-success">FINAL</span>@endif</div><div class="small text-muted">{{ $isDone?'Completed':($rejected?'Rejected':($isCurrent?'In progress':'Pending')) }}</div>@if($isCurrent && $application->workflow?->assignedUser)<div class="small mt-1">Assigned staff: <strong>{{ $application->workflow->assignedUser->fullname }}</strong></div>@endif@if($isCurrent)<div class="mt-2">@foreach($application->workflow->duties->where('workflow_stage_id',$stage->id)->sortBy('duty.id') as $duty)<span class="badge badge-{{ $duty->completed_at?'success':'light' }} mr-1">{{ $duty->duty->name }}</span>@endforeach</div>@endif</div></div>
@endforeach
</div></div></div><div class="col-lg-4"><div class="card"><div class="card-header"><strong>Stage history</strong></div><div class="card-body">@forelse($application->workflow?->history?->sortBy('acted_at') ?? collect() as $event)<div class="mb-3"><strong>{{ $event->toStage?->name ?? 'Started' }}</strong><div class="small text-muted">{{ $event->acted_at?->format('d M Y, H:i') }}</div>@if($event->comment)<div class="small mt-1">{{ $event->comment }}</div>@endif</div>@empty<div class="text-muted">No workflow history yet.</div>@endforelse</div></div><a href="{{ route('student.applications.show',$application) }}" class="btn btn-light border btn-block">Back to application</a></div></div>
@endsection
