@extends('layouts.admin')
@section('title','Application '.$application->reference_number)
@section('page_title','Application Details')
@section('page_description',$application->reference_number)
@section('content')
@if(session('success')) <div class="alert alert-success">{{ session('success') }}</div> @endif
@if($errors->any()) <div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
<div class="row"><div class="col-xl-8 mb-3">
<div class="card"><div class="card-header d-flex justify-content-between align-items-center"><h3 class="card-title">{{ $application->applicationWindow->name }}</h3><span class="badge badge-primary">{{ str_replace('_',' ',$application->status) }}</span></div><div class="card-body">
@if($application->isEditable())
<form method="POST" action="{{ route('student.applications.update',$application) }}">@csrf @method('PUT')
<div class="form-row"><div class="form-group col-md-6"><label>Current year of study</label><select name="current_study_year" class="form-control" required>@for($year=1;$year<=8;$year++)<option value="{{ $year }}" @selected($application->current_study_year==$year)>Year {{ $year }}</option>@endfor</select></div><div class="form-group col-md-3"><label>Training start</label><input type="date" name="training_start_date" class="form-control" min="{{ now()->format('Y-m-d') }}" value="{{ $application->training_start_date?->format('Y-m-d') }}" required></div><div class="form-group col-md-3"><label>Training end</label><input type="date" name="training_end_date" class="form-control" min="{{ now()->addDay()->format('Y-m-d') }}" value="{{ $application->training_end_date?->format('Y-m-d') }}" required></div></div>
<div class="form-group"><label>Reason for application</label><textarea name="reason_for_application" class="form-control" rows="4" minlength="20" maxlength="5000" required>{{ $application->reason_for_application }}</textarea></div>
<div class="form-group"><label>Areas of interest</label><textarea name="interests" class="form-control" rows="4" minlength="10" maxlength="5000" required>{{ $application->interests }}</textarea></div>
<div class="form-group"><label>Expected objectives</label><textarea name="expected_objectives" class="form-control" rows="4" minlength="20" maxlength="5000" required>{{ $application->expected_objectives }}</textarea></div>
<div class="form-group"><label>Additional notes</label><textarea name="notes" class="form-control" rows="3" maxlength="5000">{{ $application->notes }}</textarea></div>
<button class="btn btn-primary">Save draft</button>
</form>
@else
<div class="row"><div class="col-md-6 mb-3"><small class="text-muted d-block">Reference</small><strong>{{ $application->reference_number }}</strong></div><div class="col-md-6 mb-3"><small class="text-muted d-block">Training type</small><strong>{{ $application->applicationWindow->trainingType->name }}</strong></div><div class="col-md-6 mb-3"><small class="text-muted d-block">Current year</small><strong>Year {{ $application->current_study_year }}</strong></div><div class="col-md-6 mb-3"><small class="text-muted d-block">Training dates</small><strong>{{ $application->training_start_date?->format('d M Y') }} - {{ $application->training_end_date?->format('d M Y') }}</strong></div></div>
<hr><small class="text-muted d-block">Reason for application</small><p>{{ $application->reason_for_application }}</p><small class="text-muted d-block">Areas of interest</small><p>{{ $application->interests }}</p><small class="text-muted d-block">Expected objectives</small><p>{{ $application->expected_objectives }}</p><small class="text-muted d-block">Additional notes</small><p class="mb-0">{{ $application->notes ?: 'None' }}</p>
@endif
</div><div class="card-footer d-flex justify-content-between"><a href="{{ route('student.applications.index') }}" class="btn btn-light border">Back</a><div>@if($application->isEditable())<form method="POST" action="{{ route('student.applications.submit',$application) }}" class="d-inline">@csrf<button class="btn btn-success" type="submit">Submit application</button></form>@endif @if(in_array($application->status,['DRAFT','SUBMITTED','RETURNED'],true))<form method="POST" action="{{ route('student.applications.cancel',$application) }}" class="d-inline ml-1">@csrf<button class="btn btn-outline-danger" type="submit">Cancel</button></form>@endif</div></div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Application documents</h3><span class="ml-auto small text-muted">Validated by format, MIME type and size</span></div><div class="card-body">@if($application->isEditable())<form method="POST" action="{{ route('student.applications.documents.store',$application) }}" enctype="multipart/form-data" class="mb-4">@csrf<div class="form-row align-items-end"><div class="form-group col-md-5"><label>Document type</label><select name="document_type_id" class="form-control" required><option value="">Select document</option>@foreach($documentTypes as $type)<option value="{{ $type->id }}">{{ $type->name }}{{ $type->is_required?' *':'' }}</option>@endforeach</select></div><div class="form-group col-md-5"><label>File</label><input type="file" name="document" class="form-control-file" accept=".pdf,.jpg,.jpeg,.png,.doc,.docx" required></div><div class="form-group col-md-2"><button class="btn btn-primary btn-block">Upload</button></div></div></form>@endif<div class="row">@forelse($application->documents as $document)<div class="col-md-6 mb-3"><div class="border rounded p-3 h-100"><strong>{{ $document->documentType->name }}</strong><div class="small text-muted text-truncate">{{ $document->original_name }}</div><div class="mt-3"><a href="{{ route('student.applications.documents.download',[$application,$document]) }}" class="btn btn-sm btn-outline-primary">Download</a>@if($application->isEditable())<form method="POST" action="{{ route('student.applications.documents.destroy',[$application,$document]) }}" class="d-inline float-right">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Remove</button></form>@endif</div></div></div>@empty<div class="col-12 text-muted">No documents uploaded yet.</div>@endforelse</div></div></div>
</div><div class="col-xl-4 mb-3"><div class="card"><div class="card-header"><h3 class="card-title">Document requirements</h3></div><div class="card-body">@foreach($documentTypes as $type)<div class="d-flex justify-content-between border-bottom py-2"><span>{{ $type->name }}</span><span class="badge badge-{{ $application->documents->contains('document_type_id',$type->id)?'success':($type->is_required?'warning':'light') }}">{{ $application->documents->contains('document_type_id',$type->id)?'Uploaded':($type->is_required?'Required':'Optional') }}</span></div>@endforeach</div></div>
@if($application->workflow)<div class="card"><div class="card-header"><h3 class="card-title">Workflow history</h3></div><div class="card-body">@foreach($application->workflow->history->sortBy('acted_at') as $event)<div class="mb-3"><strong>{{ $event->toStage?->name ?? 'Started' }}</strong><div class="small text-muted">{{ $event->acted_at?->format('d M Y, H:i') }}</div>@if($event->comment)<div class="small mt-1">{{ $event->comment }}</div>@endif</div>@endforeach</div></div>@endif
</div></div>
@endsection
