@extends('layouts.admin')
@section('title',$workflow->name)
@section('page_title',$workflow->name)
@section('page_description','Versioned workflow configuration')
@section('content')
<div class="card mb-3"><div class="card-header d-flex align-items-center"><h3 class="card-title">Workflow versions</h3><form class="ml-auto" method="POST" action="{{ route('admin.workflows.versions.store',$workflow) }}">@csrf<input type="hidden" name="change_summary" value="New workflow revision"><button class="btn btn-sm btn-primary">Create new version</button></form></div><div class="card-body"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Version</th><th>Status</th><th>Published</th><th>Change summary</th></tr></thead><tbody>@foreach($workflow->versions->sortByDesc('version') as $version)<tr><td>v{{ $version->version }}</td><td><span class="badge badge-{{ $version->status==='PUBLISHED'?'success':($version->status==='DRAFT'?'warning':'secondary') }}">{{ $version->status }}</span></td><td>{{ $version->published_at?->format('d M Y, H:i') ?? '—' }}</td><td>{{ $version->change_summary ?: '—' }}</td></tr>@endforeach</tbody></table></div></div></div>
@if($draft)<div class="card"><div class="card-header"><h3 class="card-title">Edit draft v{{ $draft->version }}</h3></div><form method="POST" action="{{ route('admin.workflows.versions.update',$draft) }}">@csrf @method('PUT')<div class="card-body">
<div id="stage-list">@foreach($draft->stages->sortBy('stage_order') as $i=>$stage)<div class="border rounded p-3 mb-2 stage-row"><div class="form-row"><div class="form-group col-md-4"><label>Stage name</label><input name="stages[{{ $i }}][name]" class="form-control" value="{{ $stage->name }}" required></div><div class="form-group col-md-3"><label>Code</label><input name="stages[{{ $i }}][code]" class="form-control" value="{{ $stage->code }}" required></div><div class="form-group col-md-4"><label>Required permission</label><input name="stages[{{ $i }}][required_permission]" class="form-control" value="{{ $stage->required_permission }}" placeholder="applications.review"></div><div class="form-group col-md-1"><label>Final</label><input type="checkbox" name="stages[{{ $i }}][is_terminal]" value="1" class="form-control" style="height:auto" @checked($stage->is_terminal)></div></div></div>@endforeach</div>
<button type="button" class="btn btn-sm btn-outline-primary" id="add-stage">Add stage</button><div class="small text-muted mt-2">Stages are routed in order. Publishing creates immutable routing transitions for this version.</div>
</div><div class="card-footer d-flex justify-content-between"><button class="btn btn-primary">Save draft</button><button formaction="{{ route('admin.workflows.versions.publish',$draft) }}" formmethod="POST" class="btn btn-success" onclick="return confirm('Publish this workflow version? Published versions are immutable.')">Publish version</button></div></form></div>
@else<div class="alert alert-light border">There is no editable draft. Create a new version to make changes without modifying an already published workflow.</div>@endif
@push('scripts')<script>document.getElementById('add-stage')?.addEventListener('click',()=>{const list=document.getElementById('stage-list'),i=list.querySelectorAll('.stage-row').length;const row=document.createElement('div');row.className='border rounded p-3 mb-2 stage-row';row.innerHTML=`<div class="form-row"><div class="form-group col-md-4"><label>Stage name</label><input name="stages[${i}][name]" class="form-control" required></div><div class="form-group col-md-3"><label>Code</label><input name="stages[${i}][code]" class="form-control" required></div><div class="form-group col-md-4"><label>Required permission</label><input name="stages[${i}][required_permission]" class="form-control"></div><div class="form-group col-md-1"><label>Final</label><input type="checkbox" name="stages[${i}][is_terminal]" value="1" class="form-control" style="height:auto"></div></div>`;list.appendChild(row);});</script>@endpush
@endsection
