@extends('layouts.admin')
@section('title',$workflow->name)
@section('page_title',$workflow->name)
@section('page_description','Configure workflow versions, responsibilities, stages and application routing.')
@section('page_actions')<form method="POST" action="{{ route('admin.workflows.versions.store',$workflow) }}">@csrf<input type="hidden" name="change_summary" value="New workflow revision"><button class="btn btn-primary clay-btn-primary"><i class="fas fa-code-branch mr-1"></i>Create New Version</button></form>@endsection
@section('content')
@if($errors->any())<div class="alert alert-danger clay-card border-0 mb-3"><strong>Configuration needs attention:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="clay-card mb-4"><div class="clay-card-body"><div class="clay-section-heading mb-0"><span class="clay-icon"><i class="fas fa-project-diagram"></i></span><div><h3>{{ $workflow->name }}</h3><p>{{ $workflow->description ?: 'Versioned application workflow' }} · {{ $workflow->trainingType?->name ?? 'All training types' }}</p></div></div></div></div>
<div class="clay-card mb-4"><div class="clay-card-body"><div class="d-flex justify-content-between align-items-center mb-3"><div><h3 class="h5 font-weight-bold mb-1">Versions</h3><p class="clay-muted small mb-0">Published versions remain immutable. Edit a draft or create a new version.</p></div></div><div class="table-responsive"><table class="table clay-table mb-0"><thead><tr><th>Version</th><th>Status</th><th>Published</th><th>Change summary</th></tr></thead><tbody>@foreach($workflow->versions->sortByDesc('version') as $version)<tr><td class="font-weight-bold">v{{ $version->version }}</td><td><span class="badge clay-badge badge-{{ $version->status==='PUBLISHED'?'success':($version->status==='DRAFT'?'warning':'secondary') }}">{{ $version->status }}</span></td><td>{{ $version->published_at?->format('d M Y, H:i') ?? '—' }}</td><td>{{ $version->change_summary ?: '—' }}</td></tr>@endforeach</tbody></table></div></div></div>
@if($draft)<form method="POST" action="{{ route('admin.workflows.versions.update',$draft) }}" id="workflow-editor">@csrf @method('PUT')
<div class="clay-card mb-4"><div class="clay-card-body"><div class="d-flex justify-content-between align-items-start mb-4"><div><h3 class="h5 font-weight-bold mb-1">Workflow editor · v{{ $draft->version }}</h3><p class="clay-muted small mb-0">Define the path an application follows and who is responsible at each step.</p></div><span class="badge clay-badge badge-warning">DRAFT</span></div>
<div class="form-group mb-0"><label>Starting stage</label><select name="starting_stage_code" id="starting-stage" class="custom-select" required>@foreach($draft->stages->sortBy('stage_order') as $stage)<option value="{{ $stage->code }}" @selected($stage->is_starting)>{{ $stage->name }}</option>@endforeach</select><small class="clay-muted">This is the first stage assigned when a submitted application enters this workflow.</small></div>
</div></div>
<div class="clay-card mb-4"><div class="clay-card-body"><div class="d-flex align-items-center justify-content-between mb-3"><div><h3 class="h5 font-weight-bold mb-1">Stages</h3><p class="clay-muted small mb-0">Assign the team responsible for each stage.</p></div><button type="button" class="btn btn-sm btn-outline-primary clay-btn-outline" id="add-stage"><i class="fas fa-plus mr-1"></i>Add Stage</button></div><div id="stage-list">
@foreach($draft->stages->sortBy('stage_order') as $i=>$stage)
<div class="clay-stage stage-row"><div class="clay-stage-header"><div class="clay-stage-title"><span class="clay-step">{{ $i+1 }}</span><span class="stage-heading">{{ $stage->name }}</span>@if($stage->is_starting)<span class="clay-start-badge">Starting</span>@endif</div><button type="button" class="btn btn-sm btn-light clay-btn-secondary remove-stage"><i class="fas fa-trash-alt"></i></button></div><div class="form-row"><div class="form-group col-md-6"><label>Stage name</label><input name="stages[{{ $i }}][name]" class="form-control stage-name" value="{{ $stage->name }}" required></div><div class="form-group col-md-6"><label>Stage code</label><input name="stages[{{ $i }}][code]" class="form-control stage-code" value="{{ $stage->code }}" required></div><div class="form-group col-md-6"><label>Responsible role</label><select name="stages[{{ $i }}][responsible_role_id]" class="custom-select"><option value="">Any authorized role</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected($stage->responsible_role_id==$role->id)>{{ $role->name }}</option>@endforeach</select></div><div class="form-group col-md-6"><label>Stage capability</label><select name="stages[{{ $i }}][required_permission]" class="custom-select"><option value="">No additional capability</option>@foreach($permissions as $permission)<option value="{{ $permission->slug }}" @selected($stage->required_permission===$permission->slug)>{{ $permission->name }}@if($permission->slug) · {{ $permission->slug }}@endif</option>@endforeach</select></div><div class="form-group col-md-6 mb-0"><label class="d-block">Stage type</label><label class="mb-0 mr-3"><input type="checkbox" name="stages[{{ $i }}][is_terminal]" value="1" @checked($stage->is_terminal)> Final stage</label></div></div></div>
@endforeach
</div></div></div>
<div class="clay-card mb-4"><div class="clay-card-body"><div class="d-flex align-items-center justify-content-between mb-3"><div><h3 class="h5 font-weight-bold mb-1">Transitions</h3><p class="clay-muted small mb-0">Define what an authorized reviewer can do from each stage.</p></div><button type="button" class="btn btn-sm btn-outline-primary clay-btn-outline" id="add-transition"><i class="fas fa-plus mr-1"></i>Add Transition</button></div><div id="transition-list">
@foreach($draft->transitions as $i=>$transition)
<div class="clay-transition transition-row"><div class="clay-transition-header"><div class="clay-flow"><span class="clay-flow-pill from-label">{{ $transition->fromStage->name }}</span><span class="clay-flow-arrow"><i class="fas fa-arrow-right"></i></span><span class="clay-flow-pill action-label">{{ $transition->label }}</span><span class="clay-flow-arrow"><i class="fas fa-arrow-right"></i></span><span class="clay-flow-pill to-label">{{ $transition->toStage->name }}</span></div><button type="button" class="btn btn-sm btn-light clay-btn-secondary remove-transition"><i class="fas fa-trash-alt"></i></button></div><div class="form-row"><div class="form-group col-md-4"><label>From stage</label><select name="transitions[{{ $i }}][from_code]" class="custom-select from-code" required>@foreach($draft->stages as $stage)<option value="{{ $stage->code }}" @selected($stage->id===$transition->from_stage_id)>{{ $stage->name }}</option>@endforeach</select></div><div class="form-group col-md-4"><label>Action</label><select name="transitions[{{ $i }}][action]" class="custom-select action-select" required>@foreach($actions as $action)<option value="{{ $action }}" @selected($transition->action===$action)>{{ ucwords(strtolower(str_replace('_',' ',$action))) }}</option>@endforeach</select></div><div class="form-group col-md-4"><label>To stage</label><select name="transitions[{{ $i }}][to_code]" class="custom-select to-code" required>@foreach($draft->stages as $stage)<option value="{{ $stage->code }}" @selected($stage->id===$transition->to_stage_id)>{{ $stage->name }}</option>@endforeach</select></div><div class="form-group col-md-6"><label>Action button label</label><input name="transitions[{{ $i }}][label]" class="form-control label-input" value="{{ $transition->label }}" required></div><div class="form-group col-md-6"><label>Responsible role</label><select name="transitions[{{ $i }}][responsible_role_id]" class="custom-select"><option value="">Any authorized role</option>@foreach($roles as $role)<option value="{{ $role->id }}" @selected($transition->responsible_role_id==$role->id)>{{ $role->name }}</option>@endforeach</select></div><div class="form-group col-md-6 mb-0"><label>Action capability</label><select name="transitions[{{ $i }}][required_permission]" class="custom-select"><option value="">No additional capability</option>@foreach($permissions as $permission)<option value="{{ $permission->slug }}" @selected($transition->required_permission===$permission->slug)>{{ $permission->name }}@if($permission->slug) · {{ $permission->slug }}@endif</option>@endforeach</select></div><div class="form-group col-md-6 mb-0"><label class="d-block">Comment</label><label class="mb-0"><input type="checkbox" name="transitions[{{ $i }}][requires_comment]" value="1" @checked($transition->requires_comment)> Require a comment</label></div></div></div>
@endforeach
</div></div></div>
<div class="clay-card"><div class="clay-card-footer"><a href="{{ route('admin.workflows.index') }}" class="btn btn-light clay-btn-secondary">Back</a><div class="d-flex flex-wrap gap-2"><button class="btn btn-primary clay-btn-primary mr-1"><i class="fas fa-save mr-1"></i>Save Draft</button><button formaction="{{ route('admin.workflows.versions.publish',$draft) }}" formmethod="POST" class="btn btn-success" onclick="return confirm('Publish this workflow version? Published versions are immutable.')"><i class="fas fa-check mr-1"></i>Publish Version</button></div></div></div>
</form>
@else<div class="clay-card clay-empty-state"><div class="clay-empty-icon"><i class="fas fa-lock"></i></div><h3>No editable draft</h3><p>Create a new version to make changes without modifying an already published workflow.</p></div>@endif
@push('scripts')<script>
(function(){
const stageList=document.getElementById('stage-list'), transitionList=document.getElementById('transition-list'), startSelect=document.getElementById('starting-stage');
const roles=@json($roles->map(fn($r)=>['id'=>$r->id,'name'=>$r->name])->values());
const permissions=@json($permissions->map(fn($p)=>['slug'=>$p->slug,'name'=>$p->name])->values());
const actions=@json($actions->values());
const esc=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
const roleOptions=(selected='')=>'<option value="">Any authorized role</option>'+roles.map(r=>`<option value="${r.id}" ${String(selected)===String(r.id)?'selected':''}>${esc(r.name)}</option>`).join('');
const permissionOptions=(selected='')=>'<option value="">No additional capability</option>'+permissions.map(p=>`<option value="${esc(p.slug)}" ${selected===p.slug?'selected':''}>${esc(p.name)} · ${esc(p.slug)}</option>`).join('');
const actionOptions=(selected='FORWARD')=>actions.map(a=>`<option value="${a}" ${selected===a?'selected':''}>${esc(a.replaceAll('_',' ').toLowerCase().replace(/\b\w/g,c=>c.toUpperCase()))}</option>`).join('');
function stages(){return [...stageList.querySelectorAll('.stage-row')].map(row=>({code:row.querySelector('.stage-code')?.value||'',name:row.querySelector('.stage-name')?.value||'Unnamed stage'})).filter(s=>s.code);}
function options(selected=''){return stages().map(s=>`<option value="${esc(s.code)}" ${selected===s.code?'selected':''}>${esc(s.name)}</option>`).join('');}
function reindex(){stageList.querySelectorAll('.stage-row').forEach((row,i)=>{row.querySelector('.clay-step').textContent=i+1; row.querySelectorAll('[name]').forEach(el=>el.name=el.name.replace(/stages\[\d+\]/,`stages[${i}]`));});transitionList.querySelectorAll('.transition-row').forEach((row,i)=>row.querySelectorAll('[name]').forEach(el=>el.name=el.name.replace(/transitions\[\d+\]/,`transitions[${i}]`)));refreshTransitionOptions();refreshStartingOptions();}
function refreshStartingOptions(){const current=startSelect.value; startSelect.innerHTML=options(current); if([...startSelect.options].some(o=>o.value===current)) startSelect.value=current; updateStartBadges();}
function updateStartBadges(){stageList.querySelectorAll('.stage-row').forEach(row=>{let badge=row.querySelector('.clay-start-badge');const selected=row.querySelector('.stage-code')?.value===startSelect.value;if(selected&&!badge){badge=document.createElement('span');badge.className='clay-start-badge';badge.textContent='Starting';row.querySelector('.clay-stage-title').appendChild(badge);}if(!selected&&badge)badge.remove();});}
function refreshTransitionOptions(){transitionList.querySelectorAll('.transition-row').forEach(row=>{const from=row.querySelector('.from-code'),to=row.querySelector('.to-code'),fromVal=from.value,toVal=to.value;from.innerHTML=options(fromVal);to.innerHTML=options(toVal);from.value=fromVal;to.value=toVal;updateFlow(row);});}
function updateFlow(row){const from=row.querySelector('.from-code'),to=row.querySelector('.to-code'),action=row.querySelector('.label-input');const fromLabel=row.querySelector('.from-label'),toLabel=row.querySelector('.to-label'),actionLabel=row.querySelector('.action-label');if(fromLabel)fromLabel.textContent=from?.selectedOptions[0]?.text||'From stage';if(toLabel)toLabel.textContent=to?.selectedOptions[0]?.text||'To stage';if(actionLabel)actionLabel.textContent=action?.value||'Action';}
function addStage(){const i=stageList.querySelectorAll('.stage-row').length;const row=document.createElement('div');row.className='clay-stage stage-row';row.innerHTML=`<div class="clay-stage-header"><div class="clay-stage-title"><span class="clay-step">${i+1}</span><span class="stage-heading">New stage</span></div><button type="button" class="btn btn-sm btn-light clay-btn-secondary remove-stage"><i class="fas fa-trash-alt"></i></button></div><div class="form-row"><div class="form-group col-md-6"><label>Stage name</label><input name="stages[${i}][name]" class="form-control stage-name" required></div><div class="form-group col-md-6"><label>Stage code</label><input name="stages[${i}][code]" class="form-control stage-code" required></div><div class="form-group col-md-6"><label>Responsible role</label><select name="stages[${i}][responsible_role_id]" class="custom-select">${roleOptions()}</select></div><div class="form-group col-md-6"><label>Stage capability</label><select name="stages[${i}][required_permission]" class="custom-select">${permissionOptions()}</select></div><div class="form-group col-md-6 mb-0"><label class="d-block">Stage type</label><label class="mb-0"><input type="checkbox" name="stages[${i}][is_terminal]" value="1"> Final stage</label></div></div>`;stageList.appendChild(row);reindex();}
function addTransition(){const i=transitionList.querySelectorAll('.transition-row').length;const list=stages();const first=list[0]?.code||'',second=list[1]?.code||first;const row=document.createElement('div');row.className='clay-transition transition-row';row.innerHTML=`<div class="clay-transition-header"><div class="clay-flow"><span class="clay-flow-pill from-label">${esc(list[0]?.name||'From stage')}</span><span class="clay-flow-arrow"><i class="fas fa-arrow-right"></i></span><span class="clay-flow-pill action-label">Forward</span><span class="clay-flow-arrow"><i class="fas fa-arrow-right"></i></span><span class="clay-flow-pill to-label">${esc(list[1]?.name||list[0]?.name||'To stage')}</span></div><button type="button" class="btn btn-sm btn-light clay-btn-secondary remove-transition"><i class="fas fa-trash-alt"></i></button></div><div class="form-row"><div class="form-group col-md-4"><label>From stage</label><select name="transitions[${i}][from_code]" class="custom-select from-code" required>${options(first)}</select></div><div class="form-group col-md-4"><label>Action</label><select name="transitions[${i}][action]" class="custom-select action-select" required>${actionOptions()}</select></div><div class="form-group col-md-4"><label>To stage</label><select name="transitions[${i}][to_code]" class="custom-select to-code" required>${options(second)}</select></div><div class="form-group col-md-6"><label>Action button label</label><input name="transitions[${i}][label]" class="form-control label-input" value="Forward" required></div><div class="form-group col-md-6"><label>Responsible role</label><select name="transitions[${i}][responsible_role_id]" class="custom-select">${roleOptions()}</select></div><div class="form-group col-md-6 mb-0"><label>Action capability</label><select name="transitions[${i}][required_permission]" class="custom-select">${permissionOptions()}</select></div><div class="form-group col-md-6 mb-0"><label class="d-block">Comment</label><label class="mb-0"><input type="checkbox" name="transitions[${i}][requires_comment]" value="1"> Require a comment</label></div></div>`;transitionList.appendChild(row);reindex();}
document.getElementById('add-stage')?.addEventListener('click',addStage);document.getElementById('add-transition')?.addEventListener('click',addTransition);stageList?.addEventListener('click',e=>{if(e.target.closest('.remove-stage')){if(stageList.querySelectorAll('.stage-row').length<=1)return;const row=e.target.closest('.stage-row');const was=row.querySelector('.stage-code')?.value===startSelect.value;row.remove();reindex();if(was)startSelect.value=startSelect.options[0]?.value||'';updateStartBadges();}});transitionList?.addEventListener('click',e=>{if(e.target.closest('.remove-transition'))e.target.closest('.transition-row').remove();reindex();});stageList?.addEventListener('input',e=>{if(e.target.matches('.stage-name,.stage-code')){e.target.closest('.stage-row').querySelector('.stage-heading').textContent=e.target.closest('.stage-row').querySelector('.stage-name').value||'New stage';refreshStartingOptions();}});startSelect?.addEventListener('change',updateStartBadges);transitionList?.addEventListener('input',e=>{if(e.target.matches('.label-input'))updateFlow(e.target.closest('.transition-row'));});
refreshStartingOptions();refreshTransitionOptions();
})();
</script>@endpush
@endsection
