@extends('layouts.admin')
@section('title',$workflow->name)
@section('page_title',$workflow->name)
@section('page_description','Versioned workflow configuration')
@section('content')
@if(session('success')) <div class="alert alert-success">{{ session('success') }}</div> @endif
@if($errors->any()) <div class="alert alert-danger"><ul class="mb-0">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div> @endif
<div class="card mb-3"><div class="card-header d-flex align-items-center"><h3 class="card-title">Workflow versions</h3><form class="ml-auto" method="POST" action="{{ route('admin.workflows.versions.store',$workflow) }}">@csrf<input type="hidden" name="change_summary" value="New workflow revision"><button class="btn btn-sm btn-primary">Create new version</button></form></div><div class="card-body"><div class="table-responsive"><table class="table mb-0"><thead><tr><th>Version</th><th>Status</th><th>Published</th><th>Change summary</th></tr></thead><tbody>@foreach($workflow->versions->sortByDesc('version') as $version)<tr><td>v{{ $version->version }}</td><td><span class="badge badge-{{ $version->status==='PUBLISHED'?'success':($version->status==='DRAFT'?'warning':'secondary') }}">{{ $version->status }}</span></td><td>{{ $version->published_at?->format('d M Y, H:i') ?? '—' }}</td><td>{{ $version->change_summary ?: '—' }}</td></tr>@endforeach</tbody></table></div></div></div>
@if($draft)<form method="POST" action="{{ route('admin.workflows.versions.update',$draft) }}">@csrf @method('PUT')
<div class="card mb-3"><div class="card-header"><h3 class="card-title">Stages — draft v{{ $draft->version }}</h3></div><div class="card-body"><div id="stage-list">@foreach($draft->stages->sortBy('stage_order') as $i=>$stage)<div class="border rounded p-3 mb-2 stage-row"><div class="form-row"><div class="form-group col-md-4"><label>Stage name</label><input name="stages[{{ $i }}][name]" class="form-control stage-name" value="{{ $stage->name }}" required></div><div class="form-group col-md-3"><label>Code</label><input name="stages[{{ $i }}][code]" class="form-control stage-code" value="{{ $stage->code }}" required></div><div class="form-group col-md-4"><label>Stage permission</label><input name="stages[{{ $i }}][required_permission]" class="form-control" value="{{ $stage->required_permission }}" placeholder="applications.review"></div><div class="form-group col-md-1"><label>Final</label><input type="checkbox" name="stages[{{ $i }}][is_terminal]" value="1" class="form-control" style="height:auto" @checked($stage->is_terminal)></div></div></div>@endforeach</div><button type="button" class="btn btn-sm btn-outline-primary" id="add-stage">Add stage</button></div></div>
<div class="card mb-3"><div class="card-header d-flex align-items-center"><h3 class="card-title">Transitions</h3><button type="button" class="btn btn-sm btn-outline-primary ml-auto" id="add-transition">Add transition</button></div><div class="card-body"><p class="small text-muted">Transitions are explicit. Use actions such as FORWARD, RETURN, REJECT, ACCEPT or ASSIGN_SUPERVISOR and protect each action with its own permission.</p><div id="transition-list">@foreach($draft->transitions as $i=>$transition)<div class="border rounded p-3 mb-2 transition-row"><div class="form-row"><div class="form-group col-md-2"><label>From</label><select name="transitions[{{ $i }}][from_code]" class="form-control from-code" required>@foreach($draft->stages as $stage)<option value="{{ $stage->code }}" @selected($stage->id===$transition->from_stage_id)>{{ $stage->name }}</option>@endforeach</select></div><div class="form-group col-md-2"><label>To</label><select name="transitions[{{ $i }}][to_code]" class="form-control to-code" required>@foreach($draft->stages as $stage)<option value="{{ $stage->code }}" @selected($stage->id===$transition->to_stage_id)>{{ $stage->name }}</option>@endforeach</select></div><div class="form-group col-md-2"><label>Action</label><input name="transitions[{{ $i }}][action]" class="form-control" value="{{ $transition->action }}" required></div><div class="form-group col-md-2"><label>Label</label><input name="transitions[{{ $i }}][label]" class="form-control" value="{{ $transition->label }}" required></div><div class="form-group col-md-3"><label>Permission</label><input name="transitions[{{ $i }}][required_permission]" class="form-control" value="{{ $transition->required_permission }}" placeholder="applications.forward"></div><div class="form-group col-md-1"><label>Comment</label><input type="checkbox" name="transitions[{{ $i }}][requires_comment]" value="1" class="form-control" style="height:auto" @checked($transition->requires_comment)></div></div></div>@endforeach</div></div></div>
<div class="card"><div class="card-footer d-flex justify-content-between"><a href="{{ route('admin.workflows.index') }}" class="btn btn-light border">Back</a><div><button class="btn btn-primary mr-1">Save draft</button><button formaction="{{ route('admin.workflows.versions.publish',$draft) }}" formmethod="POST" class="btn btn-success" onclick="return confirm('Publish this workflow version? Published versions are immutable.')">Publish version</button></div></div></div>
</form>
@else<div class="alert alert-light border">There is no editable draft. Create a new version to make changes without modifying an already published workflow.</div>@endif
@push('scripts')<script>
const stageList=document.getElementById('stage-list'), transitionList=document.getElementById('transition-list');
function stageOptions(){return [...document.querySelectorAll('.stage-code')].map((input,i)=>({code:input.value,name:document.querySelectorAll('.stage-name')[i]?.value||input.value}));}
function optionMarkup(){return stageOptions().map(s=>`<option value="${s.code}">${s.name}</option>`).join('');}
document.getElementById('add-stage')?.addEventListener('click',()=>{const i=stageList.querySelectorAll('.stage-row').length;const row=document.createElement('div');row.className='border rounded p-3 mb-2 stage-row';row.innerHTML=`<div class="form-row"><div class="form-group col-md-4"><label>Stage name</label><input name="stages[${i}][name]" class="form-control stage-name" required></div><div class="form-group col-md-3"><label>Code</label><input name="stages[${i}][code]" class="form-control stage-code" required></div><div class="form-group col-md-4"><label>Stage permission</label><input name="stages[${i}][required_permission]" class="form-control"></div><div class="form-group col-md-1"><label>Final</label><input type="checkbox" name="stages[${i}][is_terminal]" value="1" class="form-control" style="height:auto"></div></div>`;stageList.appendChild(row);});
document.getElementById('add-transition')?.addEventListener('click',()=>{const i=transitionList.querySelectorAll('.transition-row').length;const row=document.createElement('div');row.className='border rounded p-3 mb-2 transition-row';row.innerHTML=`<div class="form-row"><div class="form-group col-md-2"><label>From</label><select name="transitions[${i}][from_code]" class="form-control from-code" required>${optionMarkup()}</select></div><div class="form-group col-md-2"><label>To</label><select name="transitions[${i}][to_code]" class="form-control to-code" required>${optionMarkup()}</select></div><div class="form-group col-md-2"><label>Action</label><input name="transitions[${i}][action]" class="form-control" value="FORWARD" required></div><div class="form-group col-md-2"><label>Label</label><input name="transitions[${i}][label]" class="form-control" value="Forward" required></div><div class="form-group col-md-3"><label>Permission</label><input name="transitions[${i}][required_permission]" class="form-control" value="applications.forward"></div><div class="form-group col-md-1"><label>Comment</label><input type="checkbox" name="transitions[${i}][requires_comment]" value="1" class="form-control" style="height:auto"></div></div>`;transitionList.appendChild(row);});
</script>@endpush
@endsection
