@extends('layouts.admin')
@section('title',$staff->exists?'Edit Staff':'Create Staff')
@section('page_title',$staff->exists?'Edit Staff':'Create Staff')
@section('page_description','Manage account, roles and effective permissions.')
@section('content')
<form method="POST" action="{{ $staff->exists ? route('admin.staff.update',$staff) : route('admin.staff.store') }}">@csrf @if($staff->exists) @method('PUT') @endif
<div class="row"><div class="col-lg-7"><div class="card"><div class="card-header"><h3 class="card-title">Account details</h3></div><div class="card-body"><div class="form-group"><label>Full name</label><input name="fullname" class="form-control" value="{{ old('fullname',$staff->fullname) }}" required></div><div class="form-row"><div class="form-group col-md-6"><label>Email</label><input type="email" name="email" class="form-control" value="{{ old('email',$staff->email) }}" required></div><div class="form-group col-md-6"><label>Username</label><input name="username" class="form-control" value="{{ old('username',$staff->username) }}" required></div></div><div class="form-group"><label>Phone</label><input name="phone" class="form-control" value="{{ old('phone',$staff->phone) }}"></div><div class="form-row"><div class="form-group col-md-6"><label>{{ $staff->exists?'New password (optional)':'Password' }}</label><input type="password" name="password" class="form-control" {{ $staff->exists?'':'required' }} minlength="12"></div><div class="form-group col-md-6"><label>Confirm password</label><input type="password" name="password_confirmation" class="form-control" {{ $staff->exists?'':'required' }} minlength="12"></div></div>@if($staff->exists)<div class="custom-control custom-switch"><input type="checkbox" class="custom-control-input" id="active" name="is_active" value="1" @checked(old('is_active',$staff->is_active))><label class="custom-control-label" for="active">Account active</label></div>@else<input type="hidden" name="is_active" value="1">@endif</div></div></div>
<div class="col-lg-5"><div class="card"><div class="card-header"><h3 class="card-title">Roles</h3></div><div class="card-body">@foreach($roles as $role)<div class="custom-control custom-checkbox mb-2"><input class="custom-control-input" type="checkbox" name="role_ids[]" value="{{ $role->id }}" id="role{{ $role->id }}" @checked(old('role_ids',$staff->roles->pluck('id')->all()) && in_array($role->id,old('role_ids',$staff->roles->pluck('id')->all())))><label class="custom-control-label" for="role{{ $role->id }}"><strong>{{ $role->name }}</strong><span class="d-block small text-muted">{{ $role->description }}</span></label></div>@endforeach</div></div>
<div class="card"><div class="card-header"><h3 class="card-title">Direct permissions</h3></div><div class="card-body"><div class="small text-muted mb-3">These permissions are added directly to this staff account in addition to role permissions.</div>@foreach($permissions as $permission)<div class="custom-control custom-checkbox mb-2"><input class="custom-control-input" type="checkbox" name="permission_ids[]" value="{{ $permission->id }}" id="permission{{ $permission->id }}" @checked(in_array($permission->id,old('permission_ids',$staff->permissions->pluck('id')->all())))><label class="custom-control-label" for="permission{{ $permission->id }}">{{ $permission->name }}<span class="d-block small text-muted">{{ $permission->slug }}</span></label></div>@endforeach</div></div></div></div>
<div class="d-flex justify-content-between"><a href="{{ route('admin.staff.index') }}" class="btn btn-light border">Cancel</a><button class="btn btn-primary">{{ $staff->exists?'Save changes':'Create staff account' }}</button></div>
</form>
@endsection
